<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Eccube\Entity\Customer' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserInterface.php';
include_once $this->targetDirs[3].'/src/Eccube/Entity/Customer.php';

return $this->services['autowired.Eccube\\Entity\\Customer'] = new \Eccube\Entity\Customer();
