<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Security\Core\User\CustomerProvider' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/Eccube/Security/Core/User/CustomerProvider.php';

return $this->services['Eccube\\Security\\Core\\User\\CustomerProvider'] = new \Eccube\Security\Core\User\CustomerProvider(${($_ = isset($this->services['Eccube\\Repository\\CustomerRepository']) ? $this->services['Eccube\\Repository\\CustomerRepository'] : $this->load('getCustomerRepositoryService.php')) && false ?: '_'});
