<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\Composer\ComposerServiceInterface' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/Composer/ComposerServiceFactory.php';

return $this->services['Eccube\\Service\\Composer\\ComposerServiceInterface'] = \Eccube\Service\Composer\ComposerServiceFactory::createService($this);
