<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\EntityProxyService' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/EntityProxyService.php';

return $this->services['Eccube\\Service\\EntityProxyService'] = new \Eccube\Service\EntityProxyService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, $this);
