<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\LoadDataFixturesEccubeCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once $this->targetDirs[3].'/src/Eccube/Command/LoadDataFixturesEccubeCommand.php';

$this->services['Eccube\\Command\\LoadDataFixturesEccubeCommand'] = $instance = new \Eccube\Command\LoadDataFixturesEccubeCommand($this);

$instance->setName('eccube:fixtures:load');

return $instance;
