<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\MailService' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/MailService.php';

return $this->services['Eccube\\Service\\MailService'] = new \Eccube\Service\MailService(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\MailTemplateRepository']) ? $this->services['Eccube\\Repository\\MailTemplateRepository'] : $this->load('getMailTemplateRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\MailHistoryRepository']) ? $this->services['Eccube\\Repository\\MailHistoryRepository'] : $this->load('getMailHistoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\BaseInfoRepository']) ? $this->services['Eccube\\Repository\\BaseInfoRepository'] : $this->getBaseInfoRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
