<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Security\Core\User\MemberProvider' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/Eccube/Security/Core/User/MemberProvider.php';

return $this->services['Eccube\\Security\\Core\\User\\MemberProvider'] = new \Eccube\Security\Core\User\MemberProvider(${($_ = isset($this->services['Eccube\\Repository\\MemberRepository']) ? $this->services['Eccube\\Repository\\MemberRepository'] : $this->load('getMemberRepositoryService.php')) && false ?: '_'});
