<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\PurchaseFlow\Processor\OrderNoProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemHolderPreprocessor.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/Processor/OrderNoProcessor.php';

return $this->services['Eccube\\Service\\PurchaseFlow\\Processor\\OrderNoProcessor'] = new \Eccube\Service\PurchaseFlow\Processor\OrderNoProcessor(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\OrderRepository']) ? $this->services['Eccube\\Repository\\OrderRepository'] : $this->getOrderRepositoryService()) && false ?: '_'});
