<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\OrderStateMachine' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/OrderStateMachine.php';

return $this->services['Eccube\\Service\\OrderStateMachine'] = new \Eccube\Service\OrderStateMachine(${($_ = isset($this->services['state_machine.order']) ? $this->services['state_machine.order'] : $this->getStateMachine_OrderService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\Master\\OrderStatusRepository']) ? $this->services['Eccube\\Repository\\Master\\OrderStatusRepository'] : $this->load('getOrderStatusRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\PurchaseFlow\\Processor\\PointProcessor']) ? $this->services['Eccube\\Service\\PurchaseFlow\\Processor\\PointProcessor'] : $this->load('getPointProcessorService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\PurchaseFlow\\Processor\\StockReduceProcessor']) ? $this->services['Eccube\\Service\\PurchaseFlow\\Processor\\StockReduceProcessor'] : $this->load('getStockReduceProcessorService.php')) && false ?: '_'});
