<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\Admin\ProductClassMatrixType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Eccube/Form/Type/Admin/ProductClassMatrixType.php';

return $this->services['Eccube\\Form\\Type\\Admin\\ProductClassMatrixType'] = new \Eccube\Form\Type\Admin\ProductClassMatrixType();
