<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator..fgqmgd' shared service.

return $this->services['service_locator..fgqmgd'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['translator' => function () {
    return ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'};
}]);
