<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.xpds6wt' shared service.

return $this->services['service_locator.xpds6wt'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['orderPdfService' => function () {
    $f = function (\Eccube\Service\OrderPdfService $v = null) { return $v; }; return $f(${($_ = isset($this->services['Eccube\\Service\\OrderPdfService']) ? $this->services['Eccube\\Service\\OrderPdfService'] : $this->load('getOrderPdfServiceService.php')) && false ?: '_'});
}]);
