<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SeShareButton4\Repository\ShareButtonConfigRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SeShareButton4/Repository/ShareButtonConfigRepository.php';

return $this->services['Plugin\\SeShareButton4\\Repository\\ShareButtonConfigRepository'] = new \Plugin\SeShareButton4\Repository\ShareButtonConfigRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
