<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator..u15ucm' shared service.

return $this->services['service_locator..u15ucm'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['TargetPayment' => function () {
    $f = function (\Eccube\Entity\Payment $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Payment']) ? $this->services['autowired.Eccube\\Entity\\Payment'] : ($this->services['autowired.Eccube\\Entity\\Payment'] = new \Eccube\Entity\Payment())) && false ?: '_'});
}]);
