<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ufjm28y' shared service.

return $this->services['service_locator.ufjm28y'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Block' => function () {
    $f = function (\Eccube\Entity\Block $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Block']) ? $this->services['autowired.Eccube\\Entity\\Block'] : ($this->services['autowired.Eccube\\Entity\\Block'] = new \Eccube\Entity\Block())) && false ?: '_'});
}, 'cacheUtil' => function () {
    $f = function (\Eccube\Util\CacheUtil $v = null) { return $v; }; return $f(${($_ = isset($this->services['Eccube\\Util\\CacheUtil']) ? $this->services['Eccube\\Util\\CacheUtil'] : ($this->services['Eccube\\Util\\CacheUtil'] = new \Eccube\Util\CacheUtil(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}, $this))) && false ?: '_'});
}, 'fs' => function () {
    return ${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())) && false ?: '_'};
}]);
