<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ue2rfk6' shared service.

return $this->services['service_locator.ue2rfk6'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Product' => function () {
    $f = function (\Eccube\Entity\Product $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Product']) ? $this->services['autowired.Eccube\\Entity\\Product'] : ($this->services['autowired.Eccube\\Entity\\Product'] = new \Eccube\Entity\Product())) && false ?: '_'});
}, 'cacheUtil' => function () {
    $f = function (\Eccube\Util\CacheUtil $v = null) { return $v; }; return $f(${($_ = isset($this->services['Eccube\\Util\\CacheUtil']) ? $this->services['Eccube\\Util\\CacheUtil'] : ($this->services['Eccube\\Util\\CacheUtil'] = new \Eccube\Util\CacheUtil(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}, $this))) && false ?: '_'});
}]);
