<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Eccube\Service\SystemService' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/SystemService.php';

if ($lazyLoad) {
    return $this->services['Eccube\\Service\\SystemService'] = $this->createProxy('SystemService_f79b835', function () {
        return \SystemService_f79b835::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSystemServiceService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Eccube\Service\SystemService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, $this);
