<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.1ntkucm' shared service.

return $this->services['service_locator.1ntkucm'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['em' => function () {
    $f = function (\Doctrine\ORM\EntityManager $v) { return $v; }; return $f(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
}]);
