<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.xejafah' shared service.

return $this->services['service_locator.xejafah'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['TaxRule' => function () {
    $f = function (\Eccube\Entity\TaxRule $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\TaxRule']) ? $this->services['autowired.Eccube\\Entity\\TaxRule'] : ($this->services['autowired.Eccube\\Entity\\TaxRule'] = new \Eccube\Entity\TaxRule())) && false ?: '_'});
}]);
