<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.fi377eb' shared service.

return $this->services['service_locator.fi377eb'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['CustomerAddress' => function () {
    $f = function (\Eccube\Entity\CustomerAddress $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\CustomerAddress']) ? $this->services['autowired.Eccube\\Entity\\CustomerAddress'] : ($this->services['autowired.Eccube\\Entity\\CustomerAddress'] = new \Eccube\Entity\CustomerAddress())) && false ?: '_'});
}]);
