<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SeShareButton4\SeShareButton4Event' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/SeShareButton4/SeShareButton4Event.php';

return $this->services['Plugin\\SeShareButton4\\SeShareButton4Event'] = new \Plugin\SeShareButton4\SeShareButton4Event(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\SeShareButton4\\Repository\\ShareButtonConfigRepository']) ? $this->services['Plugin\\SeShareButton4\\Repository\\ShareButtonConfigRepository'] : $this->load('getShareButtonConfigRepositoryService.php')) && false ?: '_'});
