<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRbvixd9\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRbvixd9/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRbvixd9.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerRbvixd9\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerRbvixd9\EccubeProdProjectContainer([
    'container.build_hash' => 'Rbvixd9',
    'container.build_id' => 'd3318e8c',
    'container.build_time' => 1607493341,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRbvixd9');
