<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\SeShareButton4\Form\Type\Admin\ConfigType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/SeShareButton4/Form/Type/Admin/ConfigType.php';

return $this->services['Plugin\\SeShareButton4\\Form\\Type\\Admin\\ConfigType'] = new \Plugin\SeShareButton4\Form\Type\Admin\ConfigType();
