<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Extension\HelpTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/src/Eccube/Form/Extension/HelpTypeExtension.php';

return $this->services['Eccube\\Form\\Extension\\HelpTypeExtension'] = new \Eccube\Form\Extension\HelpTypeExtension();
