<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Eccube\Entity\Master\ProductStatus' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/src/Eccube/Entity/Master/AbstractMasterEntity.php';
include_once $this->targetDirs[3].'/src/Eccube/Entity/Master/ProductStatus.php';

return $this->services['autowired.Eccube\\Entity\\Master\\ProductStatus'] = new \Eccube\Entity\Master\ProductStatus();
