<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\PurchaseFlow\Processor\StockReduceProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseProcessor.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/Processor/AbstractPurchaseProcessor.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/Processor/StockReduceProcessor.php';

return $this->services['Eccube\\Service\\PurchaseFlow\\Processor\\StockReduceProcessor'] = new \Eccube\Service\PurchaseFlow\Processor\StockReduceProcessor(${($_ = isset($this->services['Eccube\\Repository\\ProductStockRepository']) ? $this->services['Eccube\\Repository\\ProductStockRepository'] : $this->load('getProductStockRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
