<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\Admin\SearchCustomerType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Eccube/Form/Type/Admin/SearchCustomerType.php';

return $this->services['Eccube\\Form\\Type\\Admin\\SearchCustomerType'] = new \Eccube\Form\Type\Admin\SearchCustomerType(${($_ = isset($this->services['Eccube\\Repository\\Master\\CustomerStatusRepository']) ? $this->services['Eccube\\Repository\\Master\\CustomerStatusRepository'] : $this->load('getCustomerStatusRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
