<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.sw1vkjt' shared service.

return $this->services['service_locator.sw1vkjt'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['ProductStatus' => function () {
    $f = function (\Eccube\Entity\Master\ProductStatus $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Master\\ProductStatus']) ? $this->services['autowired.Eccube\\Entity\\Master\\ProductStatus'] : ($this->services['autowired.Eccube\\Entity\\Master\\ProductStatus'] = new \Eccube\Entity\Master\ProductStatus())) && false ?: '_'});
}, 'cacheUtil' => function () {
    $f = function (\Eccube\Util\CacheUtil $v = null) { return $v; }; return $f(${($_ = isset($this->services['Eccube\\Util\\CacheUtil']) ? $this->services['Eccube\\Util\\CacheUtil'] : ($this->services['Eccube\\Util\\CacheUtil'] = new \Eccube\Util\CacheUtil(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'}, $this))) && false ?: '_'});
}]);
