<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\ShippingMultipleType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Eccube/Form/Type/ShippingMultipleType.php';

return $this->services['Eccube\\Form\\Type\\ShippingMultipleType'] = new \Eccube\Form\Type\ShippingMultipleType(${($_ = isset($this->services['Eccube\\Repository\\ShippingRepository']) ? $this->services['Eccube\\Repository\\ShippingRepository'] : $this->load('getShippingRepositoryService.php')) && false ?: '_'});
