<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Eccube\Entity\Shipping' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Entity/AbstractEntity.php';
include_once $this->targetDirs[3].'/src/Eccube/Entity/NameTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Entity/Shipping.php';

return $this->services['autowired.Eccube\\Entity\\Shipping'] = new \Eccube\Entity\Shipping();
