<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\SchemaService' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/SchemaService.php';

return $this->services['Eccube\\Service\\SchemaService'] = new \Eccube\Service\SchemaService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\PluginContext']) ? $this->services['Eccube\\Service\\PluginContext'] : $this->load('getPluginContextService.php')) && false ?: '_'});
