<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.kffkdfa' shared service.

return $this->services['service_locator.kffkdfa'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Customer' => function () {
    $f = function (\Eccube\Entity\Customer $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Customer']) ? $this->services['autowired.Eccube\\Entity\\Customer'] : ($this->services['autowired.Eccube\\Entity\\Customer'] = new \Eccube\Entity\Customer())) && false ?: '_'});
}]);
