<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gbqrwem' shared service.

return $this->services['service_locator.gbqrwem'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Member' => function () {
    $f = function (\Eccube\Entity\Member $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Member']) ? $this->services['autowired.Eccube\\Entity\\Member'] : ($this->services['autowired.Eccube\\Entity\\Member'] = new \Eccube\Entity\Member())) && false ?: '_'});
}]);
