<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ucvjk4z' shared service.

return $this->services['service_locator.ucvjk4z'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Template' => function () {
    $f = function (\Eccube\Entity\Template $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Template']) ? $this->services['autowired.Eccube\\Entity\\Template'] : ($this->services['autowired.Eccube\\Entity\\Template'] = new \Eccube\Entity\Template())) && false ?: '_'});
}]);
