<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.bktvonm' shared service.

return $this->services['service_locator.bktvonm'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Tag' => function () {
    $f = function (\Eccube\Entity\Tag $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Tag']) ? $this->services['autowired.Eccube\\Entity\\Tag'] : ($this->services['autowired.Eccube\\Entity\\Tag'] = new \Eccube\Entity\Tag())) && false ?: '_'});
}]);
