<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.llt.3ln' shared service.

return $this->services['service_locator.llt.3ln'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Plugin' => function () {
    $f = function (\Eccube\Entity\Plugin $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Plugin']) ? $this->services['autowired.Eccube\\Entity\\Plugin'] : ($this->services['autowired.Eccube\\Entity\\Plugin'] = new \Eccube\Entity\Plugin())) && false ?: '_'});
}]);
