<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.k2nqggf' shared service.

return $this->services['service_locator.k2nqggf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['Delivery' => function () {
    $f = function (\Eccube\Entity\Delivery $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\Delivery']) ? $this->services['autowired.Eccube\\Entity\\Delivery'] : ($this->services['autowired.Eccube\\Entity\\Delivery'] = new \Eccube\Entity\Delivery())) && false ?: '_'});
}]);
