<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.rkjbrpx' shared service.

return $this->services['service_locator.rkjbrpx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['ClassName' => function () {
    $f = function (\Eccube\Entity\ClassName $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Eccube\\Entity\\ClassName']) ? $this->services['autowired.Eccube\\Entity\\ClassName'] : ($this->services['autowired.Eccube\\Entity\\ClassName'] = new \Eccube\Entity\ClassName())) && false ?: '_'});
}]);
