<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\EventListener\TruncateHyphenListener' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Form/EventListener/TruncateHyphenListener.php';

return $this->services['Eccube\\Form\\EventListener\\TruncateHyphenListener'] = new \Eccube\Form\EventListener\TruncateHyphenListener();
